# Generated by Django 4.0.4 on 2022-05-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_assignment_group_reviewer_group_alter_review_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='assigneeid',
        ),
    ]
