# Generated by Django 4.0.4 on 2022-05-24 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_reviewer_assigneeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='body',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, default='a', null=True, upload_to='uploadFiles/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='body',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploadFiles/'),
        ),
    ]
