# Generated by Django 4.0.4 on 2022-05-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_assignment_body_assignment_file_alter_upload_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='assgeneral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.assignment'),
        ),
    ]
