# Generated by Django 4.0.4 on 2022-05-27 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_reviewer_assgeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='assignmentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.assignment'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='body',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/reviewFiles/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
