# Generated by Django 4.0.4 on 2022-05-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_reviewer_assignmentid_reviewer_body_reviewer_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='body',
        ),
        migrations.RemoveField(
            model_name='review',
            name='file',
        ),
    ]
