# Generated by Django 4.0.4 on 2022-05-27 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_remove_review_body_remove_review_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='duedate',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='duetime',
            field=models.TimeField(default='23:59', null=True),
        ),
    ]
