# Generated by Django 4.0.4 on 2022-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_reviewer_created_reviewer_duedate_reviewer_duetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='duedate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='duetime',
            field=models.TimeField(default='23:59'),
        ),
    ]
