# Generated by Django 4.0.4 on 2022-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='/pictures/course.png', null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reviewFiles/'),
        ),
    ]
