# Generated by Django 4.0.4 on 2022-05-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_assignmentgeneral_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='picture',
            field=models.ImageField(blank=True, default='/pictures/review.png', null=True, upload_to='pictures/'),
        ),
    ]
